excluded:
  - Pods
  - Cartography
  - build
disabled_rules:
  - cyclomatic_complexity
  - trailing_whitespace
  - line_length
  - legacy_constructor
  - function_parameter_count
  - multiple_closures_with_trailing_closure
identifier_name:
    min_length:
        warning: 1
function_body_length: 100
